ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

source ~/.dotfiles/local/antigen.zsh
source ~/.dotfiles/local/pip-completion.zsh
source ~/.dotfiles/zsh/keybinds.zsh

[[ "$TERM_PROGRAM" == "iTerm.app" ]] && source ~/.iterm2_shell_integration.`basename $SHELL`

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Autosuggest from history
antigen bundle zsh-users/zsh-autosuggestions

# NVM plugin
antigen bundle lukechilds/zsh-nvm

# Purity theme
antigen bundle mafredri/zsh-async
antigen bundle meister/pure

# Syntax Highlighting command line (NOTE! Must be the last one)
zstyle ':bracketed-paste-magic' active-widgets '.self-*'
antigen bundle zsh-users/zsh-syntax-highlighting

# Include additional config from ~/.local.zshrc
[[ -f ~/.local.zshrc ]] && source ~/.local.zshrc

# Tell antigen that you're done.
antigen apply

# Load local configuration
[[ -f ~/.dotfiles/local/env.zsh ]] && source ~/.dotfiles/local/env.zsh