ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
DISABLE_UPDATE_PROMPT=true
PLATFORM=$(uname)
export ANTIGEN_CACHE=~/.antigen-cache

# Load local configurations
[[ -f ~/.dotfiles/local/env.zsh ]] && source ~/.dotfiles/local/env.zsh
[[ -f ~/.dotfiles/local/pip-completion.zsh ]] && source ~/.dotfiles/local/pip-completion.zsh

# Load Antigen package manager
source ~/.dotfiles/antigen/antigen.zsh
source ~/.dotfiles/zsh/keybinds.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

if [[ $PLATFORM == 'Darwin' ]]; then
  # In case if iTerm include shell integration script (disabled for now)
  # [[ "$TERM_PROGRAM" == "iTerm.app" ]] && source ~/.iterm2_shell_integration.`basename $SHELL`
  antigen bundle xcode
elif [[ $PLATFORM == 'Linux' ]]; then
  antigen bundle ubuntu
fi

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found

# VIM Vundle cmd line script
antigen bundle vundle

# Autosuggest from history
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

# NVM plugin
# export NVM_NO_USE=true
export NVM_AUTO_USE=true
antigen bundle lukechilds/zsh-nvm

# Pure theme
export PURE_NODE_TRACK=1
antigen bundle mafredri/zsh-async
antigen bundle meister/pure

# antigen bundle tylerreckart/hyperzsh
#antigen bundle denysdovhan/spaceship-zsh-theme

# Include additional config from ~/.local.zshrc
[ -f ~/.local.zshrc ] && source ~/.local.zshrc

# Syntax Highlighting command line (NOTE! Must be the last one)
zstyle ':bracketed-paste-magic' active-widgets '.self-*'
antigen bundle zsh-users/zsh-syntax-highlighting

# Tell antigen that you're done.
antigen apply
